/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Cleaned for TopoStitch demo usage.
*/

import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

const MODEL_PATH = "/command_module_apollo_11.glb";

export function Apollo11CommandModule(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["x3d-cm-exterior-filler"].geometry}
        material={materials["Default OBJ.002"]}
        position={[-69.43, -148.893, -28.968]}
        rotation={[1.763, -0.429, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["x3d-cm-exterior-shell-90k-uvs-150k-unwrapped"].geometry
        }
        material={materials["Default OBJ.001"]}
        position={[-69.43, -148.893, -28.968]}
        rotation={[1.763, -0.429, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["x3d-cm-exterior-top-160k-uvs-150k-unwrapped"].geometry}
        material={materials["Default OBJ"]}
        position={[-69.43, -148.893, -28.968]}
        rotation={[1.763, -0.429, 0.081]}
      />
    </group>
  );
}

useGLTF.preload(MODEL_PATH);
